services:
  app:
    build:
      context: ..
      dockerfile: deployments/Dockerfile
    volumes:
      - ../config:/app/config
    ports:
      - "5001:8080"
    depends_on:
      db:
        condition: service_healthy
    restart: unless-stopped

  db:
    image: postgres:latest
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=mysecretpassword
      - POSTGRES_DB=postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ../migrate/init_db.sql:/docker-entrypoint-initdb.d/init_db.sql
      - ../migrate/migrate.sql:/docker-entrypoint-initdb.d/migrate.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
    ports:
      - "5432:5432"

volumes:
  postgres_data:
